export interface vehichleOptionsTypes {
  id?: number
  src: string
  alt: string
}
export interface Meta {
  total: number
  per_page: number
  current_page: number
  last_page: number
}

export const vehichleOptions: vehichleOptionsTypes[] = [
  {
    id: 1,
    src: "/icons/car",
    alt: "car",
  },
  {
    id: 2,
    src: "/icons/tractor",
    alt: "tractor",
  },
  {
    id: 3,
    src: "/icons/moto",
    alt: "moto",
  },
]

export const dummyProductData = {
  car_id: 93171398,
  status_id: 1,
  user_id: 4406450,
  dealer_user_id: 0,
  paid_add: 0,
  photo: "9/3/1/7/1",
  pic_number: 7,
  prod_year: 2013,
  prod_month: 3,
  man_id: 12,
  car_model: "SE",
  price: 8000,
  price_usd: 8000,
  first_deposit: 0,
  price_value: 21027,
  fuel_type_id: 2,
  gear_type_id: 3,
  drive_type_id: 1,
  door_type_id: 2,
  color_id: 1,
  saloon_color_id: 2,
  cylinders: 4,
  car_run: 103000,
  car_run_km: 103000,
  car_run_dim: 1,
  engine_volume: 2500,
  airbags: 6,
  abs: true,
  esd: true,
  el_windows: true,
  conditioner: true,
  leather: false,
  disks: true,
  nav_system: true,
  central_lock: true,
  hatch: true,
  right_wheel: false,
  alarm: true,
  board_comp: true,
  hydraulics: true,
  chair_warming: true,
  climat_control: true,
  obstacle_indicator: true,
  customs_passed: true,
  client_name: "Guga Sarishvili",
  client_phone: 995577770403,
  model_id: 319,
  location_id: 2,
  parent_loc_id: 1,
  tech_inspection: true,
  checked_for_duplicates: false,
  order_number: 20,
  stickers: null,
  changable: true,
  auction: false,
  has_turbo: false,
  for_rent: false,
  rent_daily: false,
  rent_purchase: false,
  rent_insured: false,
  rent_driver: false,
  currency_id: 1,
  vehicle_type: 0,
  category_id: 1,
  vin: "",
  user_type: null,
  prom_color: 0,
  special_persons: true,
  back_camera: true,
  car_desc: "ავტომობილი არის იდეალურ მდგომარეობაში.",
  order_date: "2023-06-25 18:35:01",
  video_url: "",
  hp: 0,
  hours_used: 0,
  photo_ver: 2,
  checked: true,
  lang_type_id: 4,
  el_starter: 0,
  start_stop: true,
  trunk: false,
  windshield: false,
  inspected_in_greenway: false,
  license_number: "bt559tt",
  words_checked: 1,
  is_payd: true,
  condition_type_id: 0,
  primary_damage_type: 0,
  secondary_damage_type: 0,
  auction_has_key: 0,
  is_auction: 0,
  saloon_material_id: 2,
  map_lat: 0,
  map_long: 0,
  zoom: 0,
  predicted_price: "17084.6000",
  hdd: 0,
  map_title: "",
  has_catalyst: 1,
  tmp: "162.158.151.155",
  views: 345,
  dealerId: null,
  has_logo: null,
  logo_ver: null,
  active_ads: null,
  dealer_title: null,
  has_predicted_price: true,
  pred_first_breakpoint: 15376.140000000029,
  pred_second_breakpoint: 27335.36000000005,
  pred_min_price: 9225.684000000016,
  pred_max_price: 32802.43200000006,
  comfort_features: [
    6, 44, 11, 20, 12, 30, 31, 7, 8, 38, 28, 29, 9, 10, 23, 50, 15,
  ],
}

// Give me typescript interface for dummyProductData
// Path: utils/data.ts
